#Test environment stack for shopify upload 
#StackName: product-manager-dev
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  shopify-product-manager-service

  Sample SAM Template for shopify-product-manager-service
Globals:
  Function:
    Timeout: 20
    MemorySize: 1024

Resources:
  ProductManagerService:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: product-manager-service
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::191337286028:role/lambda-with-shopify
      Layers:
        - arn:aws:lambda:us-east-2:191337286028:layer:pandas-layer:2
      Environment:
        Variables:
          bulk_manager_table: BulkManager
          shopify_api_version: 2021-04
          s3_file_upload_bucket: shopify-file-save
          import_topic_arn: arn:aws:sns:us-east-2:191337286028:ProductImportTopic


Outputs:
  ProductManagerService:
    Description: "Shopify product manager service Function ARN"
    Value: !GetAtt ProductManagerService.Arn
